USE [master]
GO

/****** Object:  Database [Test]    Script Date: 12/30/2009 09:28:54 ******/
CREATE DATABASE [Test] ON  PRIMARY 
( NAME = N'Test', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Test.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Test_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Test_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Test] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Test] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Test] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Test] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Test] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Test] SET ARITHABORT OFF 
GO

ALTER DATABASE [Test] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Test] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Test] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Test] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Test] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Test] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Test] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Test] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Test] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Test] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Test] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Test] SET  READ_WRITE 
GO

ALTER DATABASE [Test] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Test] SET  MULTI_USER 
GO

ALTER DATABASE [Test] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Test] SET DB_CHAINING OFF 
GO


