<?xml version="1.0" encoding="utf-8"?>
<Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HtmlContent" Member="HtmlContents">
    <Type Name="HtmlContent">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="ContentData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Application_HtmlContent" Member="Application" ThisKey="ApplicationId" OtherKey="Id" Type="Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Applications">
    <Type Name="Application">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Application_HtmlContent" Member="HtmlContents" ThisKey="Id" OtherKey="ApplicationId" Type="HtmlContent" />
      <Association Name="Application_Application_UserProfile" Member="Application_UserProfiles" ThisKey="Id" OtherKey="ApplicationId" Type="Application_UserProfile" />
    </Type>
  </Table>
  <Table Name="dbo.Application_UserProfile" Member="Application_UserProfiles">
    <Type Name="Application_UserProfile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserProfileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Application_Application_UserProfile" Member="Application" ThisKey="ApplicationId" OtherKey="Id" Type="Application" IsForeignKey="true" />
      <Association Name="UserProfile_Application_UserProfile" Member="UserProfile" ThisKey="UserProfileId" OtherKey="Id" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OpenIdId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastSignInDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="UserProfile_Application_UserProfile" Member="Application_UserProfiles" ThisKey="Id" OtherKey="UserProfileId" Type="Application_UserProfile" />
    </Type>
  </Table>
</Database>